/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author mateu
 */
public class AgendaPainelFundo extends javax.swing.JFrame {

    /**
     * Creates new form AgendaPainelFundo
     */
    public AgendaPainelFundo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textObs = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAgendar = new javax.swing.JButton();
        jComboBoxServico = new javax.swing.JComboBox();
        jComboBoxCliente = new javax.swing.JComboBox();
        textHora = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        textValor = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        Nome6 = new javax.swing.JLabel();
        Nome7 = new javax.swing.JLabel();
        Nome5 = new javax.swing.JLabel();
        Nome4 = new javax.swing.JLabel();
        Nome2 = new javax.swing.JLabel();
        Nome3 = new javax.swing.JLabel();
        Nome1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        fundoPreto = new javax.swing.JLabel();
        fundoimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        textObs.setViewportView(jTextArea1);

        getContentPane().add(textObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 420, 260));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 590, 1100, 300));

        jButtonAgendar.setBackground(new java.awt.Color(153, 51, 0));
        jButtonAgendar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgendar.setText("Agendar");
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 420, 50));

        jComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cabelo", "Barba", "Barba e Cabelo" }));
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 430, 30));

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 430, 30));

        textHora.setForeground(new java.awt.Color(0, 0, 0));
        textHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHoraActionPerformed(evt);
            }
        });
        getContentPane().add(textHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 430, 30));

        textData.setForeground(new java.awt.Color(0, 0, 0));
        textData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataActionPerformed(evt);
            }
        });
        getContentPane().add(textData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 430, 30));

        textValor.setForeground(new java.awt.Color(0, 0, 0));
        textValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorActionPerformed(evt);
            }
        });
        getContentPane().add(textValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 430, 30));

        textID.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 430, 30));

        Nome6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome6.setForeground(new java.awt.Color(255, 255, 255));
        Nome6.setText("Hora");
        getContentPane().add(Nome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        Nome7.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        Nome7.setForeground(new java.awt.Color(255, 255, 255));
        Nome7.setText("Agendamento");
        getContentPane().add(Nome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        Nome5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome5.setForeground(new java.awt.Color(255, 255, 255));
        Nome5.setText("Data");
        getContentPane().add(Nome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        Nome4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome4.setForeground(new java.awt.Color(255, 255, 255));
        Nome4.setText("Observação:");
        getContentPane().add(Nome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, 20));

        Nome2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome2.setForeground(new java.awt.Color(255, 255, 255));
        Nome2.setText("Serviço");
        getContentPane().add(Nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        Nome3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome3.setForeground(new java.awt.Color(255, 255, 255));
        Nome3.setText("Valor");
        getContentPane().add(Nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        Nome1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome1.setForeground(new java.awt.Color(255, 255, 255));
        Nome1.setText("Cliente");
        getContentPane().add(Nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        Nome.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Nome.setForeground(new java.awt.Color(255, 255, 255));
        Nome.setText("ID");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        fundoPreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(fundoPreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fundoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(fundoimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void textDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataActionPerformed

    private void textHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaPainelFundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaPainelFundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaPainelFundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaPainelFundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaPainelFundo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel Nome2;
    private javax.swing.JLabel Nome3;
    private javax.swing.JLabel Nome4;
    private javax.swing.JLabel Nome5;
    private javax.swing.JLabel Nome6;
    private javax.swing.JLabel Nome7;
    private javax.swing.JLabel fundoPreto;
    private javax.swing.JLabel fundoimg;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JComboBox jComboBoxServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textHora;
    private javax.swing.JTextField textID;
    private javax.swing.JScrollPane textObs;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
